import type { University, Scholarship, SuccessStory, Professor } from './types'

export const universities: University[] = [
  {
    id: '1',
    name: 'Massachusetts Institute of Technology',
    country: 'US',
    city: 'Cambridge, MA',
    ranking: 1,
    avgGRE: 332,
    avgCGPA: 9.2,
    tuitionUSD: 58240,
    program: 'MS Computer Science',
    acceptanceRate: 3.5,
    description: 'MIT\'s EECS department is the world leader in CS research with cutting-edge labs in AI, robotics, and quantum computing.',
    avgSalaryUSD: 165000,
    programDuration: 2,
  },
  {
    id: '2',
    name: 'Stanford University',
    country: 'US',
    city: 'Stanford, CA',
    ranking: 3,
    avgGRE: 330,
    avgCGPA: 9.0,
    tuitionUSD: 57861,
    program: 'MS Computer Science',
    acceptanceRate: 5.2,
    description: 'Stanford CS sits at the heart of Silicon Valley, offering unmatched access to tech companies and startup ecosystems.',
    avgSalaryUSD: 170000,
    programDuration: 2,
  },
  {
    id: '3',
    name: 'Carnegie Mellon University',
    country: 'US',
    city: 'Pittsburgh, PA',
    ranking: 5,
    avgGRE: 328,
    avgCGPA: 8.8,
    tuitionUSD: 52952,
    program: 'MS Computer Science',
    acceptanceRate: 7.5,
    description: 'CMU\'s School of Computer Science is a top destination for AI/ML, with faculty who pioneered the field.',
    avgSalaryUSD: 155000,
    programDuration: 2,
  },
  {
    id: '4',
    name: 'University of California, Berkeley',
    country: 'US',
    city: 'Berkeley, CA',
    ranking: 8,
    avgGRE: 326,
    avgCGPA: 8.5,
    tuitionUSD: 32756,
    program: 'MS EECS',
    acceptanceRate: 8.0,
    description: 'UC Berkeley EECS combines world-class research with proximity to Silicon Valley tech hubs.',
    avgSalaryUSD: 160000,
    programDuration: 2,
  },
  {
    id: '5',
    name: 'Georgia Institute of Technology',
    country: 'US',
    city: 'Atlanta, GA',
    ranking: 15,
    avgGRE: 322,
    avgCGPA: 8.2,
    tuitionUSD: 32404,
    program: 'MS Computer Science',
    acceptanceRate: 12.0,
    description: 'Georgia Tech offers one of the best value MS CS programs with multiple specialization tracks.',
    avgSalaryUSD: 130000,
    programDuration: 2,
  },
  {
    id: '6',
    name: 'University of Illinois Urbana-Champaign',
    country: 'US',
    city: 'Champaign, IL',
    ranking: 12,
    avgGRE: 324,
    avgCGPA: 8.3,
    tuitionUSD: 36086,
    program: 'MS Computer Science',
    acceptanceRate: 10.0,
    description: 'UIUC CS is consistently ranked top 5, with strong research in systems, databases, and AI.',
    avgSalaryUSD: 140000,
    programDuration: 2,
  },
  {
    id: '7',
    name: 'University of Toronto',
    country: 'Canada',
    city: 'Toronto, ON',
    ranking: 18,
    avgGRE: 320,
    avgCGPA: 8.0,
    tuitionUSD: 28500,
    program: 'MSc Computer Science',
    acceptanceRate: 15.0,
    description: 'UofT is the birthplace of deep learning, home to Geoffrey Hinton\'s team and the Vector Institute.',
    avgSalaryUSD: 95000,
    programDuration: 2,
  },
  {
    id: '8',
    name: 'University of British Columbia',
    country: 'Canada',
    city: 'Vancouver, BC',
    ranking: 35,
    avgGRE: 316,
    avgCGPA: 7.8,
    tuitionUSD: 22000,
    program: 'MSc Computer Science',
    acceptanceRate: 18.0,
    description: 'UBC combines strong CS research with Vancouver\'s growing tech scene and quality of life.',
    avgSalaryUSD: 85000,
    programDuration: 2,
  },
  {
    id: '9',
    name: 'Imperial College London',
    country: 'UK',
    city: 'London',
    ranking: 6,
    avgGRE: 325,
    avgCGPA: 8.5,
    tuitionUSD: 42500,
    program: 'MSc Computing',
    acceptanceRate: 12.0,
    description: 'Imperial College is London\'s top STEM university with deep industry connections in fintech and AI.',
    avgSalaryUSD: 85000,
    programDuration: 1,
  },
  {
    id: '10',
    name: 'University of Oxford',
    country: 'UK',
    city: 'Oxford',
    ranking: 4,
    avgGRE: 328,
    avgCGPA: 8.8,
    tuitionUSD: 45000,
    program: 'MSc Computer Science',
    acceptanceRate: 8.0,
    description: 'Oxford CS combines centuries of academic tradition with cutting-edge research in AI safety and ML.',
    avgSalaryUSD: 90000,
    programDuration: 1,
  },
  {
    id: '11',
    name: 'ETH Zurich',
    country: 'Switzerland',
    city: 'Zurich',
    ranking: 7,
    avgGRE: 326,
    avgCGPA: 8.5,
    tuitionUSD: 1500,
    program: 'MSc Computer Science',
    acceptanceRate: 15.0,
    description: 'ETH Zurich offers world-class CS education at incredibly low tuition, with strong ties to Swiss industry.',
    avgSalaryUSD: 110000,
    programDuration: 2,
  },
  {
    id: '12',
    name: 'Technical University of Munich',
    country: 'Germany',
    city: 'Munich',
    ranking: 25,
    avgGRE: 318,
    avgCGPA: 7.5,
    tuitionUSD: 300,
    program: 'MSc Informatics',
    acceptanceRate: 20.0,
    description: 'TUM is Germany\'s top tech university with virtually free tuition and strong automotive/industry connections.',
    avgSalaryUSD: 75000,
    programDuration: 2,
  },
  {
    id: '13',
    name: 'University of Melbourne',
    country: 'Australia',
    city: 'Melbourne',
    ranking: 28,
    avgGRE: 315,
    avgCGPA: 7.5,
    tuitionUSD: 35000,
    program: 'Master of IT',
    acceptanceRate: 25.0,
    description: 'Melbourne offers top-ranked tech programs with excellent post-study work rights in Australia.',
    avgSalaryUSD: 80000,
    programDuration: 2,
  },
  {
    id: '14',
    name: 'National University of Singapore',
    country: 'Singapore',
    city: 'Singapore',
    ranking: 11,
    avgGRE: 322,
    avgCGPA: 8.2,
    tuitionUSD: 25000,
    program: 'MSc Computer Science',
    acceptanceRate: 15.0,
    description: 'NUS is Asia\'s top CS program with strong connections to Singapore\'s booming tech ecosystem.',
    avgSalaryUSD: 85000,
    programDuration: 1.5,
  },
  {
    id: '15',
    name: 'IIM Ahmedabad',
    country: 'India',
    city: 'Ahmedabad',
    ranking: 1,
    avgGRE: 0,
    avgCGPA: 8.5,
    tuitionUSD: 28000,
    program: 'PGP (MBA)',
    acceptanceRate: 2.0,
    description: 'India\'s premier management institute with the highest ROI MBA in Asia.',
    avgSalaryUSD: 45000,
    programDuration: 2,
  },
  {
    id: '16',
    name: 'ISB Hyderabad',
    country: 'India',
    city: 'Hyderabad',
    ranking: 3,
    avgGRE: 0,
    avgCGPA: 7.5,
    tuitionUSD: 42000,
    program: 'PGP (MBA)',
    acceptanceRate: 10.0,
    description: 'ISB\'s 1-year MBA offers fast-track career acceleration with strong global placements.',
    avgSalaryUSD: 40000,
    programDuration: 1,
  },
  {
    id: '17',
    name: 'University of Waterloo',
    country: 'Canada',
    city: 'Waterloo, ON',
    ranking: 30,
    avgGRE: 318,
    avgCGPA: 7.8,
    tuitionUSD: 20000,
    program: 'MMath Computer Science',
    acceptanceRate: 20.0,
    description: 'Waterloo is famous for its co-op programs and strong pipeline to Silicon Valley companies.',
    avgSalaryUSD: 90000,
    programDuration: 2,
  },
  {
    id: '18',
    name: 'University of Edinburgh',
    country: 'UK',
    city: 'Edinburgh',
    ranking: 20,
    avgGRE: 320,
    avgCGPA: 8.0,
    tuitionUSD: 38000,
    program: 'MSc AI',
    acceptanceRate: 15.0,
    description: 'Edinburgh\'s School of Informatics is the largest in the UK with a strong focus on AI and NLP.',
    avgSalaryUSD: 80000,
    programDuration: 1,
  },
  {
    id: '19',
    name: 'University of Michigan',
    country: 'US',
    city: 'Ann Arbor, MI',
    ranking: 10,
    avgGRE: 325,
    avgCGPA: 8.5,
    tuitionUSD: 51174,
    program: 'MS CSE',
    acceptanceRate: 9.0,
    description: 'UMich CSE offers exceptional research opportunities with strong industry recruiting.',
    avgSalaryUSD: 145000,
    programDuration: 2,
  },
  {
    id: '20',
    name: 'University of Texas at Austin',
    country: 'US',
    city: 'Austin, TX',
    ranking: 14,
    avgGRE: 323,
    avgCGPA: 8.3,
    tuitionUSD: 30116,
    program: 'MS Computer Science',
    acceptanceRate: 11.0,
    description: 'UT Austin CS is rising fast with Austin\'s tech boom attracting top faculty and companies.',
    avgSalaryUSD: 140000,
    programDuration: 2,
  },
]

export const scholarships: Scholarship[] = [
  {
    id: '1',
    name: 'Fulbright-Nehru Master\'s Fellowship',
    provider: 'USIEF',
    amount: 3500000,
    currency: 'INR',
    country: 'US',
    deadline: '2026-05-15',
    eligibility: 'Indian citizen, CGPA > 7.5, work experience preferred',
    matchScore: 85,
    field: 'All Fields',
    type: 'Merit',
  },
  {
    id: '2',
    name: 'Chevening Scholarship',
    provider: 'UK Government',
    amount: 4000000,
    currency: 'INR',
    country: 'UK',
    deadline: '2026-11-01',
    eligibility: 'Min 2 years work exp, return to India commitment',
    matchScore: 78,
    field: 'All Fields',
    type: 'Merit',
  },
  {
    id: '3',
    name: 'DAAD Scholarship',
    provider: 'German Government',
    amount: 1800000,
    currency: 'INR',
    country: 'Germany',
    deadline: '2026-10-15',
    eligibility: 'Bachelor\'s degree, strong academics',
    matchScore: 72,
    field: 'STEM',
    type: 'Merit',
  },
  {
    id: '4',
    name: 'Rotary Peace Fellowship',
    provider: 'Rotary Foundation',
    amount: 5000000,
    currency: 'INR',
    country: 'US',
    deadline: '2026-05-31',
    eligibility: 'Strong leadership, community service',
    matchScore: 65,
    field: 'Peace Studies',
    type: 'Need',
  },
  {
    id: '5',
    name: 'Commonwealth Scholarship',
    provider: 'CSC UK',
    amount: 3500000,
    currency: 'INR',
    country: 'UK',
    deadline: '2026-12-20',
    eligibility: 'Citizen of Commonwealth country, strong academic record',
    matchScore: 80,
    field: 'All Fields',
    type: 'Merit',
  },
  {
    id: '6',
    name: 'Stanford Knight-Hennessy Scholarship',
    provider: 'Stanford University',
    amount: 8000000,
    currency: 'INR',
    country: 'US',
    deadline: '2026-10-12',
    eligibility: 'Exceptional leadership, civic commitment',
    matchScore: 55,
    field: 'All Fields',
    type: 'Merit',
  },
  {
    id: '7',
    name: 'Vanier Canada Graduate Scholarship',
    provider: 'Canadian Government',
    amount: 4200000,
    currency: 'INR',
    country: 'Canada',
    deadline: '2026-11-01',
    eligibility: 'PhD applicants, academic excellence + leadership',
    matchScore: 60,
    field: 'All Fields',
    type: 'Research',
  },
  {
    id: '8',
    name: 'Australia Awards Scholarship',
    provider: 'Australian Government',
    amount: 5000000,
    currency: 'INR',
    country: 'Australia',
    deadline: '2026-04-30',
    eligibility: 'Developing country citizen, return home commitment',
    matchScore: 75,
    field: 'All Fields',
    type: 'Need',
  },
  {
    id: '9',
    name: 'Erasmus Mundus Joint Master',
    provider: 'European Union',
    amount: 3000000,
    currency: 'INR',
    country: 'Europe',
    deadline: '2026-01-15',
    eligibility: 'Bachelor\'s degree, strong academics',
    matchScore: 70,
    field: 'Engineering',
    type: 'Merit',
  },
  {
    id: '10',
    name: 'Inlaks Shivdasani Foundation Scholarship',
    provider: 'Inlaks Foundation',
    amount: 6000000,
    currency: 'INR',
    country: 'US',
    deadline: '2026-04-20',
    eligibility: 'Indian national, under 30, exceptional academics',
    matchScore: 68,
    field: 'All Fields',
    type: 'Merit',
  },
]

export const successStories: SuccessStory[] = [
  {
    id: '1',
    anonymizedName: 'Student A',
    backgroundUniversity: 'BITS Pilani',
    cgpa: 7.8,
    greScore: 322,
    workExp: 2,
    targetUniversity: 'Carnegie Mellon University',
    targetCountry: 'US',
    program: 'MS Computer Science',
    loanAmount: 5500000,
    nbfc: 'Avanse Financial',
    currentSalaryUSD: 155000,
    yearOfAdmission: 2022,
    avatar: '🧑‍💻',
  },
  {
    id: '2',
    anonymizedName: 'Student B',
    backgroundUniversity: 'VIT Vellore',
    cgpa: 8.2,
    greScore: 318,
    workExp: 1,
    targetUniversity: 'Georgia Institute of Technology',
    targetCountry: 'US',
    program: 'MS Computer Science',
    loanAmount: 4500000,
    nbfc: 'HDFC Credila',
    currentSalaryUSD: 135000,
    yearOfAdmission: 2023,
    avatar: '👩‍💻',
  },
  {
    id: '3',
    anonymizedName: 'Student C',
    backgroundUniversity: 'NIT Trichy',
    cgpa: 8.8,
    greScore: 328,
    workExp: 3,
    targetUniversity: 'Stanford University',
    targetCountry: 'US',
    program: 'MS Computer Science',
    loanAmount: 7500000,
    nbfc: 'Auxilo Finserve',
    currentSalaryUSD: 185000,
    yearOfAdmission: 2021,
    avatar: '🧑‍🎓',
  },
  {
    id: '4',
    anonymizedName: 'Student D',
    backgroundUniversity: 'IIIT Hyderabad',
    cgpa: 9.0,
    greScore: 330,
    workExp: 0,
    targetUniversity: 'University of Toronto',
    targetCountry: 'Canada',
    program: 'MSc Computer Science',
    loanAmount: 3500000,
    nbfc: 'MPOWER Financing',
    currentSalaryUSD: 105000,
    yearOfAdmission: 2023,
    avatar: '👨‍🔬',
  },
  {
    id: '5',
    anonymizedName: 'Student E',
    backgroundUniversity: 'DTU Delhi',
    cgpa: 7.5,
    greScore: 315,
    workExp: 4,
    targetUniversity: 'University of British Columbia',
    targetCountry: 'Canada',
    program: 'MSc Computer Science',
    loanAmount: 3000000,
    nbfc: 'Avanse Financial',
    currentSalaryUSD: 95000,
    yearOfAdmission: 2022,
    avatar: '👩‍🎓',
  },
  {
    id: '6',
    anonymizedName: 'Student F',
    backgroundUniversity: 'IIT Bombay',
    cgpa: 8.5,
    greScore: 326,
    workExp: 2,
    targetUniversity: 'ETH Zurich',
    targetCountry: 'Switzerland',
    program: 'MSc Computer Science',
    loanAmount: 1500000,
    nbfc: 'SBI Education Loan',
    currentSalaryUSD: 120000,
    yearOfAdmission: 2022,
    avatar: '🧑‍💼',
  },
  {
    id: '7',
    anonymizedName: 'Student G',
    backgroundUniversity: 'NSIT Delhi',
    cgpa: 7.2,
    greScore: 312,
    workExp: 3,
    targetUniversity: 'University of Melbourne',
    targetCountry: 'Australia',
    program: 'Master of IT',
    loanAmount: 4000000,
    nbfc: 'Auxilo Finserve',
    currentSalaryUSD: 85000,
    yearOfAdmission: 2023,
    avatar: '👨‍💻',
  },
  {
    id: '8',
    anonymizedName: 'Student H',
    backgroundUniversity: 'PEC Chandigarh',
    cgpa: 8.0,
    greScore: 320,
    workExp: 1,
    targetUniversity: 'Imperial College London',
    targetCountry: 'UK',
    program: 'MSc Computing',
    loanAmount: 5000000,
    nbfc: 'HDFC Credila',
    currentSalaryUSD: 90000,
    yearOfAdmission: 2023,
    avatar: '👩‍🔬',
  },
  {
    id: '9',
    anonymizedName: 'Student I',
    backgroundUniversity: 'COEP Pune',
    cgpa: 8.3,
    greScore: 325,
    workExp: 2,
    targetUniversity: 'University of Michigan',
    targetCountry: 'US',
    program: 'MS CSE',
    loanAmount: 6000000,
    nbfc: 'Avanse Financial',
    currentSalaryUSD: 150000,
    yearOfAdmission: 2022,
    avatar: '🧑‍🎓',
  },
  {
    id: '10',
    anonymizedName: 'Student J',
    backgroundUniversity: 'Manipal IT',
    cgpa: 7.6,
    greScore: 316,
    workExp: 5,
    targetUniversity: 'ISB Hyderabad',
    targetCountry: 'India',
    program: 'PGP (MBA)',
    loanAmount: 3500000,
    nbfc: 'HDFC Credila',
    currentSalaryUSD: 42000,
    yearOfAdmission: 2023,
    avatar: '👨‍🎓',
  },
]

export const professors: Professor[] = [
  {
    id: '1',
    name: 'Dr. Andrew Ng',
    university: 'Stanford University',
    department: 'Computer Science',
    researchAreas: ['Machine Learning', 'Deep Learning', 'AI Education'],
    email: 'ang@stanford.edu',
    hIndex: 168,
    recentPapers: ['Scaling instruction-tuned LLMs', 'Data-centric AI'],
  },
  {
    id: '2',
    name: 'Dr. Yann LeCun',
    university: 'New York University',
    department: 'Computer Science',
    researchAreas: ['Deep Learning', 'Computer Vision', 'Self-supervised Learning'],
    email: 'yann@cs.nyu.edu',
    hIndex: 155,
    recentPapers: ['A Path Towards Autonomous AI', 'V-JEPA'],
  },
  {
    id: '3',
    name: 'Dr. Fei-Fei Li',
    university: 'Stanford University',
    department: 'Computer Science',
    researchAreas: ['Computer Vision', 'Cognitive Neuroscience', 'AI Healthcare'],
    email: 'feifeili@stanford.edu',
    hIndex: 142,
    recentPapers: ['Foundation Models for Robotics', 'World Labs vision'],
  },
  {
    id: '4',
    name: 'Dr. Yoshua Bengio',
    university: 'University of Montreal',
    department: 'Computer Science',
    researchAreas: ['Deep Learning', 'Generative Models', 'AI Safety'],
    email: 'yoshua.bengio@umontreal.ca',
    hIndex: 190,
    recentPapers: ['GFlowNets', 'Causal Representation Learning'],
  },
  {
    id: '5',
    name: 'Dr. Pushmeet Kohli',
    university: 'Google DeepMind',
    department: 'AI Research',
    researchAreas: ['AI for Science', 'Protein Structure', 'Reasoning'],
    email: 'pushmeet@google.com',
    hIndex: 85,
    recentPapers: ['AlphaFold extensions', 'Mathematical reasoning'],
  },
  {
    id: '6',
    name: 'Dr. Percy Liang',
    university: 'Stanford University',
    department: 'Computer Science',
    researchAreas: ['NLP', 'Foundation Models', 'AI Evaluation'],
    email: 'pliang@stanford.edu',
    hIndex: 78,
    recentPapers: ['HELM benchmark', 'Foundation model transparency'],
  },
  {
    id: '7',
    name: 'Dr. Raquel Urtasun',
    university: 'University of Toronto',
    department: 'Computer Science',
    researchAreas: ['Autonomous Driving', 'Computer Vision', '3D Perception'],
    email: 'urtasun@cs.toronto.edu',
    hIndex: 92,
    recentPapers: ['Neural scene representations', 'Waabi world model'],
  },
  {
    id: '8',
    name: 'Dr. Anima Anandkumar',
    university: 'Caltech',
    department: 'Computing + Mathematical Sciences',
    researchAreas: ['Tensor Methods', 'Physics-informed AI', 'Scientific Computing'],
    email: 'anima@caltech.edu',
    hIndex: 75,
    recentPapers: ['Neural operators for PDEs', 'FourCastNet'],
  },
  {
    id: '9',
    name: 'Dr. Srinivasan Keshav',
    university: 'University of Cambridge',
    department: 'Computer Science',
    researchAreas: ['Computer Networks', 'Energy Systems', 'Sustainability'],
    email: 'sk818@cam.ac.uk',
    hIndex: 68,
    recentPapers: ['Carbon-aware computing', 'Grid-interactive buildings'],
  },
  {
    id: '10',
    name: 'Dr. Subhash Khot',
    university: 'New York University',
    department: 'Computer Science',
    researchAreas: ['Computational Complexity', 'Approximation Algorithms', 'Theoretical CS'],
    email: 'khot@cs.nyu.edu',
    hIndex: 42,
    recentPapers: ['Unique Games Conjecture progress', 'Hardness of approximation'],
  },
]

export const livingCostData: Record<string, { rent: number; food: number; transport: number; utilities: number; entertainment: number; currency: string }> = {
  'Mumbai': { rent: 25000, food: 12000, transport: 3000, utilities: 3000, entertainment: 5000, currency: 'INR' },
  'Delhi': { rent: 20000, food: 10000, transport: 2500, utilities: 2500, entertainment: 4000, currency: 'INR' },
  'Bangalore': { rent: 22000, food: 11000, transport: 2000, utilities: 2800, entertainment: 4500, currency: 'INR' },
  'Pune': { rent: 15000, food: 8000, transport: 1500, utilities: 2000, entertainment: 3500, currency: 'INR' },
  'Boston': { rent: 210000, food: 50000, transport: 12000, utilities: 15000, entertainment: 20000, currency: 'INR' },
  'San Francisco': { rent: 280000, food: 55000, transport: 10000, utilities: 12000, entertainment: 25000, currency: 'INR' },
  'New York': { rent: 260000, food: 55000, transport: 15000, utilities: 13000, entertainment: 25000, currency: 'INR' },
  'London': { rent: 230000, food: 45000, transport: 18000, utilities: 14000, entertainment: 20000, currency: 'INR' },
  'Toronto': { rent: 180000, food: 40000, transport: 10000, utilities: 12000, entertainment: 15000, currency: 'INR' },
  'Vancouver': { rent: 190000, food: 42000, transport: 9000, utilities: 11000, entertainment: 16000, currency: 'INR' },
  'Melbourne': { rent: 160000, food: 38000, transport: 10000, utilities: 10000, entertainment: 14000, currency: 'INR' },
  'Zurich': { rent: 250000, food: 60000, transport: 12000, utilities: 15000, entertainment: 20000, currency: 'INR' },
  'Munich': { rent: 140000, food: 35000, transport: 8000, utilities: 10000, entertainment: 12000, currency: 'INR' },
  'Singapore': { rent: 200000, food: 40000, transport: 8000, utilities: 10000, entertainment: 18000, currency: 'INR' },
  'Pittsburgh': { rent: 120000, food: 35000, transport: 7000, utilities: 10000, entertainment: 10000, currency: 'INR' },
  'Austin': { rent: 150000, food: 38000, transport: 8000, utilities: 11000, entertainment: 15000, currency: 'INR' },
}
