# SonarQube / SonarCloud project config for Kurukshetra
sonar.projectKey=Darshan1814_Kurukshetra-
sonar.projectName=Kurukshetra-
sonar.organization=darshan1814
sonar.sources=src,extension/src
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=**/node_modules/**,**/.next/**,**/extension/dist/**,**/public/**,scripts/**,**/*.css,**/*.svg,tests/**

# TypeScript + Next.js project layout
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
